version: "3.7"
services:
  eureka-server-vk:
    container_name: serviceregistry
    hostname: serviceregistry
    build: ./eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka

  zuul-server-vk:
    depends_on:
      - "eureka-server-vk"
    container_name: gateway
    hostname: gateway
    build: ./zuul
    ports:
      - "8181:8181"
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka

  register-did-service-issuer:
    depends_on:
      - "eureka-server-vk"
      - "zuul-server-vk"
    build: ./register-did-service-issuer
    volumes:
      - .:/issuer
    ports:
      - "3003:3003"
    restart: always

  register-did-service-verfier:
    depends_on:
      - "eureka-server-vk"
      - "zuul-server-vk"
    build: ./register-did-service-verfier
    volumes:
      - .:/verifier
    ports:
      - "3004:3004"
    restart: always

  register-did-ui:
    depends_on:
      - "register-did-service-issuer"
      - "register-did-service-verfier"
    build: ./register-did-ui
    volumes:
      - .:/didUI
    ports:
      - "3005:3005"
    restart: always
